// <auto-generated />
using System;
using KutubxonaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutubxonaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KutubxonaAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Abdulla Qodiriy",
                            Category = "Roman",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Title = "O'tgan kunlar",
                            Year = 1922
                        },
                        new
                        {
                            Id = 2,
                            Author = "Abdulla Qodiriy",
                            Category = "Roman",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Title = "Mehrobdan chayon",
                            Year = 1929
                        },
                        new
                        {
                            Id = 3,
                            Author = "Tohir Malik",
                            Category = "Roman",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Title = "Shaytanat",
                            Year = 1996
                        });
                });

            modelBuilder.Entity("KutubxonaAPI.Models.BookPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Content = "Yigirma sakkizinchi yilning yanvar oyining yigirma to'qqizinchi kuni edi. Bu kun ham, har kungidek, Toshkent kuchli sovuq ostida edi. Ko'cha bo'ylab tushgan qor butun shahar yuzini oqartirib turardi. Otabek o'z xonasida uxlamasdan o'tirardi. Uning xayollari uzoq, yiroq joylarga uchayotgan edi. Onasining ovozi uni xayoldan uyg'otdi.",
                            PageNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Content = "Otabek choyni iching, sovub qolyapti, deb chaqirdi onasi. Otabek o'rnidan turdi va xonadan chiqdi. Mehmonxonada otasi Yusufbek hoji o'tirardi. Otabek otasi bilan salomlashdi va dasturxon yoniga o'tirdi. Yusufbek hoji o'g'liga qarab dedi: O'g'lim, men senga bir narsa aytmoqchiman. Toshkentda bir yaxshi qiz bor. Uning ismi Kumush. Marg'ilonlik.",
                            PageNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Content = "Otabek bu so'zlardan keyin jim qoldi. U Kumushni ko'rmagan edi, lekin u haqida ko'p eshitgan edi. Kumush juda go'zal va aqlli qiz edi. Otabek o'ylab turdi va dedi: Ota, men sizning so'zingizni quloq solaman. Yusufbek hoji o'g'lining bu javobidan xursand bo'ldi. Ertaga Marg'ilonga jo'naymiz, dedi.",
                            PageNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            Content = "Mehrobdan chayon - Abdulla Qodiriyning ikkinchi mashhur tarixiy romanidir. Roman 1928-1929-yillarda yozilgan va 1929-yilda nashr etilgan. Asar XIX asrning oxiri va XX asr boshlaridagi Buxoro va Samarqand tarixiga bag'ishlangan. Roman qahramoni Anvar - yosh, bilimli va vatanparvar yigitdir.",
                            PageNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            Content = "U Buxoro madrasasida tahsil olgan va o'z xalqining ozodligi uchun kurashadi. Anvarning sevgilisi Ra'no esa amir Said Olimxonning xotini bo'lishga majbur etilgan ayoldir. Asarda Buxoro amirligining oxirgi yillaridagi vaziyat, xalq hayoti, mardlik va xiyonat, sevgi va ayriliq tasvirlanadi.",
                            PageNumber = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 2,
                            Content = "Qodiriy bu romanda ham o'zining nozik ruhshunoslik mahoratini namoyish etgan. Har bir personajning ichki kechinmalari, fikrlari va his-tuyg'ulari mohirona ko'rsatilgan. Anvar va Ra'no o'rtasidagi sevgi - sof, samimiy va fojiali. Mehrobdan chayon - faqat bir sevgi hikoyasi emas, balki butun bir davrning hikoyasidir.",
                            PageNumber = 3
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            Content = "Shaytanat - Tohir Malikning eng mashhur detektiv romanidir. Roman 1996-yilda nashr etilgan. Asar O'zbekistondagi mustaqillik yillaridagi jinoyat dunyosi haqida hikoya qiladi. Bosh qahramon - tergovchi Maxsud Asadov. U o'zining tajribasi va aql-zakovati bilan eng murakkab jinoyatlarni ochib boradi.",
                            PageNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            BookId = 3,
                            Content = "Romanda qanday qilib jinoyatchilar guruhlari paydo bo'lganligi, ular qanday ishlaganligi va qanday qilib qonun himoyachilari ular bilan kurashganligi tasvirlanadi. Asar voqealari Toshkent va boshqa shaharlarda kechadi. Maxsud o'z hamkasblari bilan birga jinoyatchilarni ushlash uchun xavfli operatsiyalarda qatnashadi.",
                            PageNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            Content = "Birinchi bobda Maxsud ofisida o'tirib, yangi ishni ko'rib chiqyapti. Yosh tadbirkor o'ldirilgan. Hech qanday guvoh yo'q, hech qanday iz qoldirilmagan. Bu juda professional ish edi. Maxsud o'z taxminlari bilan ishlay boshladi. Asar oxirida Maxsud jinoyatchini topadi. Bu roman shunchaki detektiv emas, balki hayot haqidagi falsafiy asardir.",
                            PageNumber = 3
                        });
                });

            modelBuilder.Entity("KutubxonaAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("KutubxonaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KutubxonaAPI.Models.BookPage", b =>
                {
                    b.HasOne("KutubxonaAPI.Models.Book", "Book")
                        .WithMany("Pages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("KutubxonaAPI.Models.Comment", b =>
                {
                    b.HasOne("KutubxonaAPI.Models.Book", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("KutubxonaAPI.Models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
